//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalGreen.Core.DataBase.DigitalGreenDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmerImage
    {
        public long FarmerImagesId { get; set; }
        public Nullable<long> FarmerId { get; set; }
        public string ImagePath { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual Farmer Farmer { get; set; }
    }
}
